sudo: false

os:
  - linux
  - osx x
  - windows

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

# matrix:
#   exclude:
#   - os: windows
#     python: "2.7"

# install dependencies
install:
  # - pip install -r requirements.txt
  - pip install pytest
  - pip install .

# run tests
script:
  - python -m pytest

# speed up later builds
cache:
  directories:
    - $HOME/.cache/pip

# after_success:
    # - coveralls

