sudo: false

os:
  - linux
  - osx x
  - windows

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"

# install dependencies
install:
  - pip install pytest
  - pip install .

# run tests
script:
  - python -m pytest

# speed up later builds
cache:
  directories:
    - $HOME/.cache/pip

# add this eventually
# after_success:
    # - coveralls

deploy:
  provider: pypi
  user: akaszynski
  password: $PYIP_PASS