sudo: required
dist: xenial

os:
- linux

language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'

install:
  - pip install pytest
  - pip install -e .
  - pip install pytest-cov
  - pip install codecov
  - pip install matplotlib


script:
  # Run the test suite and generate coverage report
  - pytest -v --cov keepa
  - |  # report code coverage
    if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then
      codecov
    fi


cache:
  directories:
  - "$HOME/.cache/pip"

deploy:
  provider: pypi
  user: akaszynski
  distributions: sdist
  on:
    condition: $TRAVIS_PYTHON_VERSION == 3.6
    tags: true
  password:
    secure: "Gu3rvQpzA5RPwp/gpjbgRZ5mkz0G6OGKNTnTlHsZ/r8qLKzw1bSD1uyh9JSET0hE1I5cNhI0kiOLH02wSk9cGz7VSizlnY/n8l+aMYgIxtVaIqDAXPoJOnv3ckDZyBODtQbYK05YJYxGPfij21ewiirIGefLEzSRTGoB1nu5M8Xz5krRsN3u/3dRXLgrG2cXPTBEs6c0PnUkvuLmwd8QSV54PnKN7IFhP7LX2kFS+Iuz6byYd84Y0ordgmD/gp+P+lijYsuHc0RdKP7JnmAU1TByNCC16yBGaTIjf2qtBwldar+LGXgFXiEeUXQeYak1hZN4vpf7xdq707ECcFzRglXr3q93n8AzDsMoyfb48joc6IguAwAC16V5FH3QKIzZP+pR0DkES4ZkW8e5xgoK/8OGodnUAAi2TWkT1V6QXy+qHV3GzBZA3IquuzbARoKeaO6S6ZMCoHEXxKSJd/z+JwXFIkS5zwWKC8ud6zYoEiLYmz8w9/hj1+lhKol3YcXMtBpZ5l/LcAG8vLr9XtaCaNngDiFDzmdVIlClaVpI2jWWFILpxXRpymd1WM4dhnQMTzL3gYhiKUJZINeoIOF1rEwAbjKYn0esNopuEryaK+NSVRx0WO8Ps0R/xpC+HTyMMBXBMlDhjG4dkI27gckCwUKSQJIeV0AqXXeqsH5A3c8="

notifications:
  email: false